"""
Django settings for CRTD_TECHNOLOGIES_API project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c)2*bdc0+u%5b#&0%(i00+lu$ft79b(sgjq6o3kj9bq#h%7a71'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'androidapi',
    'adminweb',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CRTD_TECHNOLOGIES_API.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['Template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CRTD_TECHNOLOGIES_API.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'crtd_technology',
        'USER': 'root',
        'PASSWORD': 'Ajay@123',
        'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }
}


# PROJECT_DIR = os.path.abspath(os.path.dirname(__file__))
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(PROJECT_DIR, 'yourdatabasename.db'),
#     }
# }

# DATABASES = {
#     'default': {
#          'NAME': 'CRTD_Technology',
#         'ENGINE': 'django.db.backends.mysql',
#         'USER': config('DB_USER'),
#         'PASSWORD': config('DB_PASSWORD',default=''),
#         'HOST': config('DB_HOSTNAME'), 
#         'OPTIONS': {
#          "init_command": "SET foreign_key_checks = 0;",
#          "init_command": "SET sql_mode= 'STRICT_TRANS_TABLES'",
#       },
#     },
#     'CRTD-RC': {
#          'NAME': 'CRTD',
#         'ENGINE': 'django.db.backends.mysql',
#         'USER': config('DB_USER'),
#         'PASSWORD': config('DB_PASSWORD',default=''),
#         'HOST': config('DB_HOSTNAME'), 
#         'OPTIONS': {
#          "init_command": "SET foreign_key_checks = 0;",
#          "init_command": "SET sql_mode= 'STRICT_TRANS_TABLES'",
#       },
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'


# STATIC_ROOT='https://crtdbucket.s3.ap-south-1.amazonaws.com/CRTD_TECHsite/index.jshttps://crtdbucket.s3.ap-south-1.amazonaws.com/CRTD_TECHsite/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "assets"),
    )

# STATICFILES_LOCATION = 'static'
# STATIC_URL = 'https://crtdbucket.s3.ap-south-1.amazonaws.com/CRTD_TECHsite/'
# STATICFILES_STORAGE = 'custom_storage.StaticStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.hostinger.com'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 465
# EMAIL_HOST_USER = "support@crtd.in" #sender's email-id
# EMAIL_HOST_PASSWORD ="Crtd@2020"   #password associated with above email-id
