# Generated by Django 3.2.4 on 2022-02-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('androidapi', '0002_remove_applied_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied',
            name='feedback',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='applied',
            name='payment_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='applied',
            name='whatsapp_status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='applyempinfo',
            name='dob',
            field=models.DateField(default=None, null=True),
        ),
    ]
