# Generated by Django 3.2.4 on 2022-02-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('androidapi', '0003_auto_20220216_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applied',
            name='whatsapp_status',
        ),
    ]
