# Generated by Django 3.2.4 on 2022-02-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('androidapi', '0004_remove_applied_whatsapp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied',
            name='whatsapp_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
