# Generated by Django 3.2.4 on 2022-01-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminweb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivationCode',
        ),
        migrations.DeleteModel(
            name='Adminlogins',
        ),
        migrations.DeleteModel(
            name='Applied',
        ),
        migrations.DeleteModel(
            name='ApplyEmpInfo',
        ),
        migrations.DeleteModel(
            name='Appversion',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Contactus',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='EmpEducations',
        ),
        migrations.DeleteModel(
            name='Empkeyskill',
        ),
        migrations.DeleteModel(
            name='JobProfile',
        ),
        migrations.DeleteModel(
            name='PassingYear',
        ),
    ]
